[tool.poetry]
name = "web"
version = "0.1.0"
description = ""
authors = ["SheltonZSL <1878858428@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
django = "^4.1.5"
fastapi = "^0.88.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
